### ISSUE TITLE
Idempotency?

### ISSUE THREAD

**Issue by thomaseyde** [horsdal/event-replay#2]
Where do you handle idempotency? I guess the `When` method shouldn't be bothered with that, because it should only care about applying the event. And you moved it out of the aggregate for a reason, which leaves the command handler. But doesn't that bloat the handler with logic that doesn't belong there?

**Comment by horsdal** [comment]
I handle idempotency in the command handler. As you suggest. If that bloats the command handler I would pull something out of it. That likely sounds like a bit of a cop out, but I don't think this is different from other objects in the system, so usual OO design principles apply. To me, it's analogous to controllers in MVC applications becoming bloated: When that happens I pull parts out to other objects. So when a command handler gets bloated I introduce other objects with some of the behavior that would otherwise be in the command handler. It's about identifying those smaller chuncks on responsibility. And remembering that we are not limited to only command handlers, aggregates and events. We can have other objects.
